'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace GlobalWeather
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.webserviceX.NET", ConfigurationName:="GlobalWeather.GlobalWeatherSoap")>  _
    Public Interface GlobalWeatherSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.webserviceX.NET/GetWeather", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetWeather(ByVal request As GlobalWeather.GetWeatherRequest) As GlobalWeather.GetWeatherResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.webserviceX.NET/GetCitiesByCountry", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetCitiesByCountry(ByVal request As GlobalWeather.GetCitiesByCountryRequest) As GlobalWeather.GetCitiesByCountryResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetWeather", WrapperNamespace:="http://www.webserviceX.NET", IsWrapped:=true)>  _
    Partial Public Class GetWeatherRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.webserviceX.NET", Order:=0)>  _
        Public CityName As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.webserviceX.NET", Order:=1)>  _
        Public CountryName As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CityName As String, ByVal CountryName As String)
            MyBase.New
            Me.CityName = CityName
            Me.CountryName = CountryName
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetWeatherResponse", WrapperNamespace:="http://www.webserviceX.NET", IsWrapped:=true)>  _
    Partial Public Class GetWeatherResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.webserviceX.NET", Order:=0)>  _
        Public GetWeatherResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetWeatherResult As String)
            MyBase.New
            Me.GetWeatherResult = GetWeatherResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetCitiesByCountry", WrapperNamespace:="http://www.webserviceX.NET", IsWrapped:=true)>  _
    Partial Public Class GetCitiesByCountryRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.webserviceX.NET", Order:=0)>  _
        Public CountryName As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CountryName As String)
            MyBase.New
            Me.CountryName = CountryName
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetCitiesByCountryResponse", WrapperNamespace:="http://www.webserviceX.NET", IsWrapped:=true)>  _
    Partial Public Class GetCitiesByCountryResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.webserviceX.NET", Order:=0)>  _
        Public GetCitiesByCountryResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetCitiesByCountryResult As String)
            MyBase.New
            Me.GetCitiesByCountryResult = GetCitiesByCountryResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface GlobalWeatherSoapChannel
        Inherits GlobalWeather.GlobalWeatherSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class GlobalWeatherSoapClient
        Inherits System.ServiceModel.ClientBase(Of GlobalWeather.GlobalWeatherSoap)
        Implements GlobalWeather.GlobalWeatherSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetWeather(ByVal request As GlobalWeather.GetWeatherRequest) As GlobalWeather.GetWeatherResponse Implements GlobalWeather.GlobalWeatherSoap.GetWeather
            Return MyBase.Channel.GetWeather(request)
        End Function
        
        Public Function GetCitiesByCountry(ByVal request As GlobalWeather.GetCitiesByCountryRequest) As GlobalWeather.GetCitiesByCountryResponse Implements GlobalWeather.GlobalWeatherSoap.GetCitiesByCountry
            Return MyBase.Channel.GetCitiesByCountry(request)
        End Function
    End Class
End Namespace
